In [103]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[6,7],[8,9]])

D = np.zeros([2,2])
C = np.zeros([2,2])
M = np.zeros([2,2])

In [104]:
for i in range(len(A)):
    for j in range((len(A))):
        C[i,j] = A[i,j] * B [j,i]
        D[i,j] += C[i,j]

In [105]:
for i in range(len(A)):
    for j in range(len(A)):
        for k in range(len(A)):
            M[i,j] += A[i,k] * B[k,j]

In [106]:
D

array([[ 6., 16.],
       [21., 36.]])

In [107]:
M

array([[22., 25.],
       [50., 57.]])

In [108]:
X = np.dot(A,B)
X

array([[22, 25],
       [50, 57]])

In [110]:
x = 4
for i in range(x):
    print('*'*(i+1))

*
**
***
****


In [111]:
a3 = np.array([[[10,11,12],[13,14,15],[16,17,18]],
              [[20,21,22],[23,24,25],[26,27,28]],
              [[30,31,32],[33,34,35],[36,37,38]]])

In [112]:
a3[1,1,:]

array([23, 24, 25])

In [114]:
a3[-2:-1,-1:,-2:-1]

array([[[27]]])

In [116]:
bases = [10,20,30,40,50,60,70,80,90,100]
idx = [1,2,3,4,5,6,7,8,9,10]

# X = bases**idx

In [117]:
list(map(lambda x,y: x**y, bases**idx))

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'list'